### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by anges244** [westdabestdb/undraw#2]
Hi! This violates the [license](https://undraw.co/license) under which unDraw illustrations are available.

**Comment by westdabestdb** [comment]
Hello, which part of the package violates unDraw license?


All images, assets and vectors published on unDraw can be used for free. You can use them for noncommercial and commercial purposes. You do not need to ask permission from or provide credit to the creator or unDraw.

**Comment by anges244** [comment]
The next part:

This license does not include the right to compile assets, vectors or images from unDraw to replicate a similar or competing service, in any form or distribute the assets in packs. This extends to automated ways to scrape, search or download the assets included on the website without our consent.

**Comment by westdabestdb** [comment]
Shit ! :( Well I respect your license and rules. Is there any way we can come to an agreement or find an alternative way for this package? I'm not sure if you know Dartlang or any programming, but what this package does is:

1- It has urls of undraw illustrations, so it still uses your platform to reach the illustrations.
2- When user puts an illustration into their app, package makes an http call to your website, gets the svg content, and change the primary color, which is `#6c63ff` for customization option.

This package doesn't give user an option to download or manipulate vectors, except change of the primary color. All svgs are served on http calls.

I saw undraw on Framer X, and it just seemed like a cool illustration package. I thought flutter developers would love to use free open source illustrations in their apps without downloading them, and accessing to those illustrations using your cdn server.

**Comment by westdabestdb** [comment]
@anges244 any updates here?

**Comment by anges244** [comment]
Hi, sorry for the late response but I had to see this matter in detail with Katerina. Unfortunately this is a violation of the unDraw license and using the urls of the illustrations is the same load for our CDN as scraping. I understand that you are coming from a good place but we have to maintain unDraw free and open, and such packages are making it much harder. However, Katerina does not want for you to discontinue it, at least for now since it's not been a problem, so let's see how it goes.

**Comment by westdabestdb** [comment]
Thank you for being so understanding and not suing my ass 😁 I'm glad this worked out for both of us. Have a great day and tell my best wishes to Katerina. I will close this issue for now, but feel free to contact me about this any time.
