### ISSUE TITLE
Offline 

### ISSUE THREAD

**Issue by alfaruqrizqi18** [westdabestdb/undraw#6]
Is it possible if I use illustration without internet connection?
Because, you will send request to this https://42f2671d685f51e10fc6-b9fcecea3e50b3b59bdc28dead054ebc.ssl.cf5.rackcdn.com/illustrations/ right? 
I need it works well when offline :( I hope you can do it hehe
Never mind, it's just my opinion

**Comment by westdabestdb** [comment]
Haha, let me implement offline caching then ;)

**Comment by nikhiljha** [comment]
@westdabestdb Could there be a way to configure what images you need locally, and then bundle those into the package? Every single image on undraw is around ~16MB, which isn't too bad but... 

(You can download them here.) https://github.com/mkhairi/undraw/tree/master/vendor/assets/images/undraw
